extern const GeoLayout lava_platform_geo[];
extern Lights1 lava_platform_Grass_lights;
extern u8 lava_platform_beachRock2_i4[];
extern Vtx lava_platform_vanish_001_mesh_layer_1_vtx_cull[8];
extern Vtx lava_platform_vanish_001_mesh_layer_1_vtx_0[32];
extern Gfx lava_platform_vanish_001_mesh_layer_1_tri_0[];
extern Gfx mat_lava_platform_Grass[];
extern Gfx mat_revert_lava_platform_Grass[];
extern Gfx lava_platform_vanish_001_mesh_layer_1[];
extern Gfx lava_platform_material_revert_render_settings[];
