extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_sand_layer1_area1_lights;
extern Lights1 bob_dl_f3d_material_lights;
extern u8 bob_dl_SUPER_MARIO_64_5F328955_0_2_all_ci8[];
extern u8 bob_dl_SUPER_MARIO_64_5F328955_0_2_all_ci8_pal_rgba16[];
extern u8 bob_dl_water_semi_transparent_ci8[];
extern u8 bob_dl_water_semi_transparent_ci8_pal_rgba16[];
extern Vtx bob_dl_Island_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Island_mesh_layer_1_vtx_0[44];
extern Gfx bob_dl_Island_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Water_mesh_layer_5_vtx_cull[8];
extern Vtx bob_dl_Water_mesh_layer_5_vtx_0[29];
extern Gfx bob_dl_Water_mesh_layer_5_tri_0[];
extern Gfx mat_bob_dl_sand_layer1_area1[];
extern Gfx mat_revert_bob_dl_sand_layer1_area1[];
extern Gfx mat_bob_dl_f3d_material[];
extern Gfx mat_revert_bob_dl_f3d_material[];
extern Gfx bob_dl_Island_mesh_layer_1[];
extern Gfx bob_dl_Water_mesh_layer_5[];
extern Gfx bob_dl_material_revert_render_settings[];
