extern u8 galaxy_background_cloud_panorama_resized_i8[];
extern Vtx galaxy_background_AAABeachBackground_mesh_vtx_cull[8];
extern Vtx galaxy_background_AAABeachBackground_mesh_vtx_0[224];
extern Gfx galaxy_background_AAABeachBackground_mesh_tri_0[];
extern Gfx mat_galaxy_background_bigtexturemode2_layer0[];
extern Gfx mat_revert_galaxy_background_bigtexturemode2_layer0[];
extern Gfx galaxy_background_AAABeachBackground_mesh[];
